### ISSUE TITLE
Transfer electron-json-storage

### ISSUE THREAD

**Issue by jviotti** [electron-userland/about#2]
Hey there!

I wrote https://github.com/jviotti/electron-json-storage long ago in order to easily store settings in Electron's user data path. The module became quite popular, and there are various feature requests that I don't have the proper time to  address, like encrypted settings, obfuscated settings, support for JSON dates, etc.

I'd love to transfer this repo here, so other contributors can help me maintain it.

**Comment by zeke** [comment]
👍  I'm in favor of moving projects to orgs to distribute the maintenance burden.

If we do move it, I would suggest adding a section to the `electron-json-storage` readme that lists alternative packages for persisting data to disk, for the benefit of Electron users weighing their options.

Two alternatives I've had success with are [electron-settings](http://ghub.io/electron-settings) and [electron-store](http://ghub.io/electron-store), both of which have synchronous APIs which are easier to work with than callbacks or promises, and in most cases the performance penalty for this synchronous behavior is minimal.

cc @nathanbuchar @sindresorhus

**Comment by jviotti** [comment]
> If we do move it, I would suggest adding a section to the electron-json-storage readme that lists alternative packages for persisting data to disk, for the benefit of Electron users weighing their options.

Sounds great to me. Correct me if I'm wrong, but I think I need to be invited to the `electron-userland` org in order to transfer it. 

I'll update the README with pointers to `electron-settings` and `electron-store` in the mean time.

**Comment by jviotti** [comment]
Done! Check the updated README!

**Comment by zeke** [comment]
New README looks great.

The Electron maintainers group has a code of conduct. Please [read and agree to it](https://docs.google.com/a/github.com/forms/d/e/1FAIpQLSctSBB3VHabqDent91LKHnGlIEJE850MGuXBH4BoOsxGoXIbg/viewform
) and we'll get you set up.

Thanks!

**Comment by jviotti** [comment]
Done, thanks a lot!

**Comment by zeke** [comment]
Thanks @jviotti I've sent you an invitation to join the org. Welcome! 🙌

**Comment by jviotti** [comment]
Awesome, thanks a lot @zeke! I'll transfer the repo very soon.
