### ISSUE TITLE
Clarify code of conduct

### ISSUE THREAD

**Issue by johnmuhl** [electron-userland/about#3]
@zeke mentioned in another issue:

> The Electron maintainers group has a code of conduct. Please read and agree to it and we'll get you set up.

This was the first I heard about that and am certain that I did not sign that when invited to the `electron-userland` group. If this is a new requirement perhaps it could be added to the description here: https://github.com/electron-userland/about

**Comment by zeke** [comment]
You're right, @johnmuhl. I was mixing up the requirements of the @electron and @electron-userland orgs. All members who join @electron must explicitly agree to the [Contributor Covenant](http://contributor-covenant.org/).

Here's a PR that adds the CoC to this org: https://github.com/electron-userland/about/pull/4
